/**
 * Compile every theme under `themes/` into `src/themes/builtin.gen.ts`.
 *
 * The built-in theme ships inside the Worker bundle, so the site renders with
 * zero setup and there is never a state with no theme. Workers can't read the
 * filesystem at runtime, and wrangler's text-module rules don't reach `bun
 * test`, so the files become one generated module that both can import.
 *
 * Text only — the built-in themes have no fonts or images of their own (they
 * load type from Google Fonts and the logo from `public/`).
 *
 *   bun run build:theme          (also runs as part of `dev` and `deploy`)
 */
import { createHash } from 'node:crypto'
import { mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { dirname, join, relative } from 'node:path'

const themesDir = join(import.meta.dir, '..', 'themes')
const out = join(import.meta.dir, '..', 'src', 'themes', 'builtin.gen.ts')

function walk(dir: string): string[] {
  return readdirSync(dir).flatMap((name) => {
    if (name.startsWith('.')) return []
    const full = join(dir, name)
    return statSync(full).isDirectory() ? walk(full) : [full]
  })
}

const themes: Record<string, { hash: string; files: Record<string, string> }> = {}
for (const name of readdirSync(themesDir).sort()) {
  const root = join(themesDir, name)
  if (!statSync(root).isDirectory()) continue
  const files: Record<string, string> = {}
  for (const full of walk(root).sort()) {
    if (full.endsWith('README.md')) continue
    files[relative(root, full).split('\\').join('/')] = readFileSync(full, 'utf8')
  }
  const hash = createHash('sha256').update(JSON.stringify(files)).digest('hex').slice(0, 10)
  themes[name] = { hash, files }
  console.log(`${name}: ${Object.keys(files).length} files, ${hash}`)
}

mkdirSync(dirname(out), { recursive: true })
writeFileSync(
  out,
  `// GENERATED by scripts/build-theme.ts from themes/*/ — do not edit.
// Edit a theme, then \`bun run build:theme\`.

export const BUILTIN_THEMES: Record<string, { hash: string; files: Record<string, string> }> = ${JSON.stringify(
    themes,
    null,
    2,
  )}
`,
)
