/**
 * Compile `themes/kolea/` into `src/themes/kolea.gen.ts`.
 *
 * The built-in theme ships inside the Worker bundle, so the site renders with
 * zero setup and there is never a state with no theme. Workers can't read the
 * filesystem at runtime, and wrangler's text-module rules don't reach `bun
 * test`, so the files become one generated module that both can import.
 *
 * Text only — the built-in theme has no fonts or images of its own (it loads
 * Inter from Google Fonts and the logo from `public/`).
 *
 *   bun run build:theme          (also runs as part of `dev` and `deploy`)
 */
import { createHash } from 'node:crypto'
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { join, relative } from 'node:path'

const root = join(import.meta.dir, '..', 'themes', 'kolea')
const out = join(import.meta.dir, '..', 'src', 'themes', 'kolea.gen.ts')

function walk(dir: string): string[] {
  return readdirSync(dir).flatMap((name) => {
    if (name.startsWith('.')) return []
    const full = join(dir, name)
    return statSync(full).isDirectory() ? walk(full) : [full]
  })
}

const files: Record<string, string> = {}
for (const full of walk(root).sort()) {
  if (full.endsWith('README.md')) continue
  files[relative(root, full).split('\\').join('/')] = readFileSync(full, 'utf8')
}

const hash = createHash('sha256').update(JSON.stringify(files)).digest('hex').slice(0, 10)

writeFileSync(
  out,
  `// GENERATED by scripts/build-theme.ts from themes/kolea/ — do not edit.
// Edit the theme, then \`bun run build:theme\`.

export const KOLEA_THEME: { name: string; hash: string; files: Record<string, string> } = ${JSON.stringify(
    { name: 'kolea', hash, files },
    null,
    2,
  )}
`,
)
console.log(`kolea theme: ${Object.keys(files).length} files, ${hash}`)
